# config file for processing functional count data 

RAW_DATA:
    # path to input raw haircut fastqs
    "/beevol/home/riemondy/Projects/various_repos/haircut_pipeline/raw_data/2019-03-20_data/haircut"

DATA:
    # path to output data files
    "../data"

HAIRCUT_FASTA:
    "/beevol/home/riemondy/Projects/various_repos/haircut_pipeline/dbases/genome/hairpin.fa"

HAIRCUT_SAMPLES:
    - JH134_2 
    - JH141_PBMC1
    - JH141_PBMC2

10X_WHITELIST:
    # known barcodes used in the 10x libraires to use for error correction
    "/cluster/software/modules-sw/cellranger/3.0.2/cellranger-cs/3.0.2/lib/python/cellranger/barcodes/737K-august-2016.txt"

CELL_BARCODES:
    # barcodes considered to be cells based on cellrange count run on mRNA
    # data
    - "/beevol/home/riemondy/Projects/various_repos/haircut_pipeline/2019-03-20_mrna/JH133/outs/filtered_feature_bc_matrix/barcodes.tsv.gz"
    - "/beevol/home/riemondy/Projects/various_repos/haircut_pipeline/2019-03-20_mrna/JH140_PBMC1/outs/filtered_feature_bc_matrix/barcodes.tsv.gz"
    - "/beevol/home/riemondy/Projects/various_repos/haircut_pipeline/2019-03-20_mrna/JH140_PBMC2/outs/filtered_feature_bc_matrix/barcodes.tsv.gz"

SRC:
    # path to directory with source code " 
    "../src"


